include ../Makefile.tests_common

# required modules
USEMODULE += gnrc_ipv6_ipsec
USEMODULE += rust_riotmodules

FEATURES_REQUIRED += rust_target

BOARD ?= native

include $(RIOTBASE)/Makefile.include
