[package]
name = "riot-module-rcoap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riot-sys = { version = "0.7.9", features = [] }
riot-wrappers = "0.8.1"


