[package]
name = "riot-module-rcoap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riot-wrappers = { version = "0.8", features = [ "set_panic_handler" ] }


